### ISSUE TITLE
compilation error with new version of AppleClang

### ISSUE THREAD

**Issue by clemaitre** [GATB/gatb-core#28]
Hi,

gatb-core does not compile any more with AppleClang 10.0.1.1001004  (it worked with AppleClang 10.0.0.10001145)
Here are the error messages:
```
gatb-core/src/gatb/debruijn/impl/BranchingAlgorithm.cpp:155:58: error: 'predecessors' following the 'template’ keyword does not refer to a template
GraphVector<Node> predecessors = graph->template predecessors (node);
gatb-core/src/gatb/debruijn/impl/BranchingAlgorithm.cpp:154:58: error: 'successors' following the 'template' keyword does not refer to a template
GraphVector<Node> successors   = graph->template successors   (node);
```
I have tested with two different commits of gatb-core f25f57b (current master) and an older one 5642ef0 (March 2018), and obtained the same errors.

Claire

**Comment by Piezoid** [comment]
I think we can safely remove the `template` keyword in those cases. 
It was useful before the [refactoring](https://github.com/GATB/gatb-core/commit/e8c2f6ef37c863910c844230e64279985531cccb) removing template arguments to `predecessors/successors`.

**Comment by clemaitre** [comment]
Thanks for the quick answer, 
it compiled when I removed the `template` keyword in the following 4 instructions:

```
gatb-core/src/gatb/debruijn/impl/BranchingAlgorithm.cpp:155
gatb-core/src/gatb/debruijn/impl/BranchingAlgorithm.cpp:154
gatb-core/src/gatb/debruijn/impl/Terminator.cpp:49
gatb-core/src/gatb/debruijn/impl/Terminator.cpp:199
```
Can you check if this is safe also in `Terminator.cpp` ?

Claire

**Comment by Piezoid** [comment]
Yes it is safe.

Worst case is the compiler complaining about [template dependent name](https://en.cppreference.com/w/cpp/language/dependent_name) that prevent the compiler to infer if the name is a template (needs `template`) a type (needs `typename`) or a variable.
A change is semantics is really unlikely.

**Comment by rchikhi** [comment]
Please go ahead and commit the fix to gatb-core, if you can, one of you two :)

**Comment by clemaitre** [comment]
Hi Rayan,

I am about to commit... but it seems that this may erase your last visisble commit on github (f25f57bb65db0870ec3c5b14af5e694c7941f567) which is not on the gforge repo : when I git pull from the gforge I fall on f58d96bbea953b37edaf455e4c3e404c89e95027, did you commit directly on github, forgetting about the gforge ? 

Claire

**Comment by rchikhi** [comment]
oh you're right! thanks for letting me know. some mistake from my part. I've now pushed my commit to gforge, you can now pull (and `git rebase -i` to avoid the merge) and commit on top of my last commit
